variables:
  projectDirectory: './'

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'custom'
    customVersion: 2.5.3
  displayName: 'Install latest Flutter SDK stable version'
    
- task: FlutterTest@0
  inputs:
   projectDirectory: $(projectDirectory)
  displayName: 'Run Flutter tests'

- task: FlutterBuild@0
  inputs:
    target: apk
    projectDirectory: $(projectDirectory)

- task: CopyFiles@2
  inputs:
   contents: '**/*.apk'
   targetFolder: '$(build.artifactStagingDirectory)'